# Use the analysis options settings from the top level of the repo (not
# the ones from above, which include the `public_member_api_docs` rule).

include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: false
  exclude:
    - "test/src/**"
    - "example/**"
    - "test/base/all_tests.dart"

linter:
  rules:
    unawaited_futures: true
    avoid_bool_literals_in_conditional_expressions: false
