name: tool_base
description: Flutter Tools' base. Use to create command line tools.
version: 1.9.5+1
homepage: https://github.com/mmcc007/tool_base
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  archive: ^2.0.9
  file: ^5.0.8
  platform: ^2.2.0
  process: ^3.0.9

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  mockito: ^4.1.0
  quiver: ^2.0.3
